### ISSUE TITLE
Сотрудник проходит аутентификацию

### ISSUE THREAD

**Issue by markshevchenko** [progmsk/angry-heads#5]
Как владелец сайта, я хочу, чтобы сотрудник, прежде чем оставить отзыв, прошёл аутентификацию на headhunter.ru, чтобы снизить количество мусорных отзывов.

### Основной сценарий
1. Сотрудник видит на сайте кнопку *Оставить отзыв*. Он вприпрыжку нажимает её, но Система кровожадно хочет аутентификации и перенаправляет его на headhunter.ru для подтверждения.
2. Headhunter.ru предупреждает сотрудника, что Система высосет всю его кровь и отберёт все его деньги, и требует немедленного согласия.
3. Сотрудник соглашается, после чего Система получает подтверждение от сайта headhunter.ru и показывает сотруднику форму нового отзыва.

### Альтернативные сценарии
- 3. Сотрудник липко потеет и отказывается предоставлять Системе свою информацию. Система получает от headhunter.ru отказ и снова показывает сотруднику главную страницу сайта.

### Задачи
- [x] Исследовать аутентификацию OAuth посредством dev.hh.ru
- [x] Реализовать аутентификацию OAuth #9 
- [x] Сохранять `access_token` и `refresh_token` #10 
- [x] Получать у hh.ru информацию о текущем пользователе #12

**Comment by markshevchenko** [comment]
# Аутентификация OAuth посредством dev.hh.ru
[Описание от Head Hunter](https://github.com/hhru/api/blob/master/docs/authorization.md)

1. На сайте сделать кнопку *Войти через Head Hunter*. Кнопка должна вести по адресу:
> https://hh.ru/oauth/authorize?response_type=code&client_id={client_id}&**state=hh**&**redirect_uri=http://angry-heads.prog.msk.ru/oauth**
